"""создание таблиц Test и TestItem

Revision ID: 1c2c07dc52bc
Revises: 
Create Date: 2026-04-24 11:32:46.676721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c2c07dc52bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city')
    op.drop_table('type_building')
    op.drop_table('country')
    op.drop_table('building')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Название', sa.VARCHAR(length=200), nullable=True),
    sa.Column('type_building_id', sa.INTEGER(), nullable=True),
    sa.Column('city_id', sa.INTEGER(), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('height', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['type_building_id'], ['type_building.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('country',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Страна', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_building',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Тип', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Город', sa.VARCHAR(length=100), nullable=True),
    sa.Column('country_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
