"""создание таблиц Test и TestItem

Revision ID: 81c5c8f7df38
Revises: 1c2c07dc52bc
Create Date: 2026-04-24 11:37:45.482440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c5c8f7df38'
down_revision = '1c2c07dc52bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('test_type', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('test_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=150), nullable=False),
    sa.Column('answer', sa.String(length=150), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_item')
    op.drop_table('test')
    # ### end Alembic commands ###
